---
# Ensure the opencast user has the same uid/gid
# so we don't run into problems on the shared file system

- name: Create group opencast
  ansible.builtin.group:
    name: "{{ opencast_user_group_name }}"
    gid: "{{ opencast_user_gid }}"

- name: Create user opencast
  ansible.builtin.user:
    name: "{{ opencast_user_name }}"
    uid: "{{ opencast_user_uid }}"
    group: "{{ opencast_user_group_name }}"
    create_home: false
