---
dependency:
  name: galaxy
  enabled: false
driver:
  name: containers
platforms:
  - name: opencast_user_centos_stream9
    image: quay.io/centos/centos:stream9
  - name: opencast_user_debian
    image: docker.io/library/debian:stable
  - name: opencast_user_ubuntu
    image: docker.io/ubuntu:latest
lint: |
  set -e
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
