---
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: oc_user_centos_stream8
    image: quay.io/centos/centos:stream8
    pre_build_image: false
  - name: oc_user_centos_stream9
    image: quay.io/centos/centos:stream9
    pre_build_image: false
  - name: oc_user_centos_7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: oc_user_debian
    image: docker.io/library/debian:bullseye
    pre_build_image: false
  - name: oc_user_ubuntu
    image: docker.io/ubuntu:latest
    pre_build_image: false
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
