---

dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: opencast-user-centos-stream8
    image: quay.io/centos/centos:stream8
    pre_build_image: false
  - name: opencast-user-centos-stream9
    image: quay.io/centos/centos:stream9
    pre_build_image: false
  - name: opencast-user-centos-8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: opencast-user-centos-7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: opencast-user-debian
    image: docker.io/pycontribs/debian
    pre_build_image: true
  - name: opencast-user-ubuntu
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
provisioner:
  name: ansible
verifier:
  name: ansible
