---

name: lint

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r .dev_requirements.txt

      - name: Run ansible-lint
        run: ansible-lint
